version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_RELEASE_VERSION}
    ports:
      - ${PUBLISH_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_RELEASE_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_RELEASE_VERSION}
    networks:
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${SUBNET_FRONT}"
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${SUBNET_BACK}"
